# Generated by Django 5.0.1 on 2024-03-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimateproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateproject',
            name='servicesNeeded',
        ),
    ]
